package com.eli.calc.shape.model;

public enum ShapeName {
	
	CIRCLE,
	SQUARE,
	EQUILATERALTRIANGLE,
	PENTAGON,
	HEXAGON,
	SPHERE,      //CIRCLE
	CUBE,        //SQUARE
	TETRAHEDRON, //EQUILATERALTRIANGLE
	//DODECAHEDRON, //PENTAGON
	TRUNCICOSAHERON  //PENTAGON, HEXAGON
}